Forced Focused
pallupz/covid-vaccine-booking pull request #153
Opened 2021-05-13 22:22 UTC by vasugamdha

Problem: The captcha window needs to set the focus manually by selecting it.
Solution: Added focus on the captacha window and focus on the input box too. (Refer 2nd commit)

1st commit: Input text was hard to understand, so, improved that too.

2021-05-14 04:15 UTC, abhinavatai commented on src/captcha.py
> +    return values['inp']
Please check suggested comments: https://github.com/bombardier-gif/covid-vaccine-booking/pull/136#pullrequestreview-659503698

2021-05-14 06:44 UTC, vasugamdha commented
@abhinavatai Please, state the reason for the suggested changes.

2021-05-14 07:56 UTC, catch-n-release requested changes
Raise PR on different branch other than "main".

2021-05-15 05:52 UTC, archit-va commented
@vasugamdha   HEY CAN YOU SHARE YOUR EDITED CODE TO ME at archit.va@gmail.com

2021-05-15 05:53 UTC, archit-va approved these changes

2021-05-15 06:48 UTC, vasugamdha commented
> @vasugamdha HEY CAN YOU SHARE YOUR EDITED CODE TO ME at [archit.va@gmail.com](mailto:archit.va@gmail.com)

you can find my final edits here-> [`captcha.py`](https://github.com/pallupz/covid-vaccine-booking/blob/a8b8571b5970735bc375369956b1687e83c96504/src/captcha.py)

2021-05-16 15:42 UTC, pallupz commented
Hi @vasugamdha - I want to incorporate the forced focus. Could you please do a quick merge from ```main```?

2021-05-16 15:43 UTC, pallupz commented
its showing changes to multiple files for some reason. I think this should be limited to ```captcha.py``` file, right?

2021-05-17 18:32 UTC, vasugamdha commented
Yes, it is limited to `captcha.py`. 
The other change is completely independent. The change in the other file is just for a bit better understanding of one particular confusing line i.e.

From:
```
minimum_slots = input(f'Filter out centers with availability less than ? Minimum {len(beneficiary_dtls)} : ')
```
To:
```
minimum_slots = input(f'Filter out centers with minimum availability of ? doses (Minimum {len(beneficiary_dtls)}) : ')
```

2021-05-17 18:37 UTC, vasugamdha commented
> Hi @vasugamdha - I want to incorporate the forced focus. Could you please do a quick merge from `main`?

Do you want me to change branch from `ext-dev/vishal` to `main`?

2021-05-18 08:02 UTC, abhishekjaiswal1989 commented
How does captcha and the booking process work after 'slots checking..' step?  It would help if you can post some screenshots so that we can refer to them for getting an idea before booking.

2021-05-18 15:34 UTC, closed without merging